version: '3'
services:
  garistory-backend:
    image: golang:1.16
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - garistory-db
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgres://garistory-db:5432/${POSTGRES_DATABASE}
    command: go run cmd/main.go

  garistory-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}