version: '3'
services:
  garistory-backend:
    image: golang:1.16-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: go run cmd/main.go
    depends_on:
      - garistory-db

  garistory-db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - garistory-db:/var/lib/postgresql/data
volumes:
  garistory-db:
    driver: local